// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPnR1ZjmPED0woLSoa3bFnRMSTKCzsnl0',
    appId: '1:856939183618:android:79e1500d26b7024c4f311b',
    messagingSenderId: '856939183618',
    projectId: 'works-d4f07',
    storageBucket: 'works-d4f07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6RXryjE-RclYN1EoIrPdgR4nXhf30rNA',
    appId: '1:856939183618:ios:66d89b6ff5eda7ee4f311b',
    messagingSenderId: '856939183618',
    projectId: 'works-d4f07',
    storageBucket: 'works-d4f07.firebasestorage.app',
    iosBundleId: 'com.mansour.works',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYky7kCeSOtpA8X8gy1pPILmqUYB8etoU',
    appId: '1:856939183618:web:8f3ee282b4b96cb34f311b',
    messagingSenderId: '856939183618',
    projectId: 'works-d4f07',
    authDomain: 'works-d4f07.firebaseapp.com',
    storageBucket: 'works-d4f07.firebasestorage.app',
    measurementId: 'G-WWPXECEK8Q',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6RXryjE-RclYN1EoIrPdgR4nXhf30rNA',
    appId: '1:856939183618:ios:66d89b6ff5eda7ee4f311b',
    messagingSenderId: '856939183618',
    projectId: 'works-d4f07',
    storageBucket: 'works-d4f07.firebasestorage.app',
    iosBundleId: 'com.mansour.works',
  );

}